version: '2'
services:
    armadillomonitor-app:
        image: armadillomonitor
        external_links:
            - armadillomonitor-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=armadilloMonitor
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    armadillomonitor-mongodb:
        extends:
            file: mongodb.yml
            service: armadillomonitor-mongodb
