version: '2'
services:
    armadillomonitor-mongodb:
        container_name: armadillomonitor-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/armadilloMonitor/mongodb/:/data/db/
